/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empmngmnt.gui;

import empmngmnt.dbutil.DBConnection;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class OptionFrame extends javax.swing.JFrame {

    /**
     * Creates new form OptionFrame
     */
    public OptionFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jrbAddEmp = new javax.swing.JRadioButton();
        jrbSearchEmp = new javax.swing.JRadioButton();
        jrbShowAllEmp = new javax.swing.JRadioButton();
        jrbQuit = new javax.swing.JRadioButton();
        btnDoTask = new javax.swing.JButton();
        jrbUpdateEmp = new javax.swing.JRadioButton();
        jrbDeleteEmp = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Employee Mangement System App");

        jrbAddEmp.setBackground(new java.awt.Color(0, 0, 0));
        jrbAddEmp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jrbAddEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrbAddEmp.setText("Add Emp");

        jrbSearchEmp.setBackground(new java.awt.Color(0, 0, 0));
        jrbSearchEmp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jrbSearchEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrbSearchEmp.setText("Search Emp");

        jrbShowAllEmp.setBackground(new java.awt.Color(0, 0, 0));
        jrbShowAllEmp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jrbShowAllEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrbShowAllEmp.setText("ShowAllEmp");

        jrbQuit.setBackground(new java.awt.Color(0, 0, 0));
        jrbQuit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jrbQuit.setForeground(new java.awt.Color(255, 255, 255));
        jrbQuit.setText("Quit");

        btnDoTask.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDoTask.setText("Do task");
        btnDoTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoTaskActionPerformed(evt);
            }
        });

        jrbUpdateEmp.setBackground(new java.awt.Color(0, 0, 0));
        jrbUpdateEmp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jrbUpdateEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrbUpdateEmp.setText("Update Employee");

        jrbDeleteEmp.setBackground(new java.awt.Color(0, 0, 0));
        jrbDeleteEmp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jrbDeleteEmp.setForeground(new java.awt.Color(255, 255, 255));
        jrbDeleteEmp.setText("Delete Employee");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbAddEmp)
                            .addComponent(jrbSearchEmp)
                            .addComponent(jrbShowAllEmp)
                            .addComponent(jrbQuit)
                            .addComponent(btnDoTask, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrbUpdateEmp)
                            .addComponent(jrbDeleteEmp))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jrbAddEmp)
                .addGap(18, 18, 18)
                .addComponent(jrbSearchEmp)
                .addGap(18, 18, 18)
                .addComponent(jrbShowAllEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jrbUpdateEmp)
                .addGap(18, 18, 18)
                .addComponent(jrbDeleteEmp)
                .addGap(18, 18, 18)
                .addComponent(jrbQuit)
                .addGap(34, 34, 34)
                .addComponent(btnDoTask)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoTaskActionPerformed
    if(validateInput()==false)
    {
        JOptionPane.showMessageDialog(null,"Please make a selection");
        return;
    }
    if(jrbAddEmp.isSelected())
    {
        AddEmployeeFrame addEmp=new AddEmployeeFrame();
        addEmp.setVisible(true);
        this.dispose();
    }
    else if(jrbSearchEmp.isSelected())
    {
        SearchEmployeeFrame searchEmp=new SearchEmployeeFrame();
        searchEmp.setVisible(true);
        this.dispose();
    }
    else if(jrbShowAllEmp.isSelected())
    {
        ViewAllEmployee viewAllEmp=new ViewAllEmployee();
        viewAllEmp.setVisible(true);
        this.dispose();
    }
    else if(jrbUpdateEmp.isSelected())
    {
        UpdateEmployeeFrame updateEmp=new UpdateEmployeeFrame();
        updateEmp.setVisible(true);
        this.dispose();
    }
    else if(jrbDeleteEmp.isSelected())
    {
        DeleteEmployeeFrame deleteEmp=new DeleteEmployeeFrame();
        deleteEmp.setVisible(true);
        this.dispose();
    }
    else
    {
        JOptionPane.showMessageDialog(null,"Thank you for using the app");
        DBConnection.closeConnection();
        System.exit(0);
    }
    }//GEN-LAST:event_btnDoTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OptionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoTask;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbAddEmp;
    private javax.swing.JRadioButton jrbDeleteEmp;
    private javax.swing.JRadioButton jrbQuit;
    private javax.swing.JRadioButton jrbSearchEmp;
    private javax.swing.JRadioButton jrbShowAllEmp;
    private javax.swing.JRadioButton jrbUpdateEmp;
    // End of variables declaration//GEN-END:variables
private boolean validateInput()
{
    if(jrbAddEmp.isSelected()==false && jrbSearchEmp.isSelected()==false && jrbShowAllEmp.isSelected()==false && jrbUpdateEmp.isSelected()==false && jrbDeleteEmp.isSelected()==false && jrbQuit.isSelected()==false)
     return false;
    return true;
}
}

